export const projectLinks = [
    {
        id : 1,
        projectName : "Youtube Clone",
        link : "https://github.com/KiranMvarma25/YouTube-Project",
        projectThumbnail : "https://www.bleepstatic.com/content/hl-images/2023/05/10/YouTube.jpeg",
        technologiesUsed : ["React", "Node.js", "Express.js", "MongoDB", "Redux", "CSS"],
        projectDescription : "Created a YouTube clone using the MERN stack, allowing users to upload, view and interact with videos, featuring user authentication, video playback and a comment section.",
    },
    {
        id : 2,
        projectName : "Shoppy Globe",
        link : "https://67220cd26f1f19701c4e35cc--fabulous-conkies-1075a4.netlify.app/",
        projectThumbnail : "https://5.imimg.com/data5/OE/JR/MY-16129639/e-commerce-application-development-service-500x500.jpg",
        technologiesUsed : ["React", "Redux", "CSS"],
        projectDescription : "Shoppy Globe is an e-commerce application built with React and CSS. The application provides users with a seamless experience to browse products, view product details, and manage their shopping cart. It leverages Redux for state management and includes dynamic routing for efficient navigation.",
    },
    {
        id : 3,
        projectName : "Chatbot",
        link : "https://github.com/KiranMvarma25/Chatbot---Full-Stack",
        projectThumbnail : "https://www.q3tech.com/wp-content/uploads/2024/06/Evolution-of-chatbots.jpg",
        technologiesUsed : ["React", "Node.js", "Express.js", "MongoDB", "CSS"],
        projectDescription : "A helpdesk chatbot application where users can interact with the chatbot to ask queries, receive responses and view chat history. Data is hardcoded in the Backend i.e., Rule-based logic for generating chatbot responses",
    },
    {
        id : 4,
        projectName : "Quiz Application",
        link : "https://brilliant-choux-4ac3bc.netlify.app/",
        projectThumbnail : "https://repository-images.githubusercontent.com/182525249/aadd7a80-54fe-11eb-9872-ccd06b8789b6",
        technologiesUsed : ["React", "Node.js", "Express.js", "MongoDB", "CSS"],
        projectDescription : "A Quiz application where users can add questions and others can answer them. The app displays the correct answer immediately after submission, ensuring an interactive and educational experience.",
    },
    // {
    //     id : 5,
    //     projectName : "",
    //     link : "",
    //     projectThumbnail : "",
    //     technologiesUsed : ["", "", ""],
    //     projectDescription : "",
    // },
    {
        id : 6,
        projectName : "Weather Forecast",
        link : "https://kiranmvarma25.github.io/Weather-Forecast/",
        projectThumbnail : "https://store-images.s-microsoft.com/image/apps.16894.c02476d2-2378-4f60-8290-b6d4b3842643.79a2ef6a-4775-4c79-8d93-9caf077660eb.1bbd88a4-0a17-4750-91a0-cd7d98f58e9d",
        technologiesUsed : ["HTML", "Tailwind CSS", "JavaScript"],
        projectDescription : "The app includes a search form to fetch data using the OpenWeather API by city name. Weather data is displayed dynamically, enhanced with emojis to represent conditions visually. A dropdown stores and displays search history using local storage, allowing users to revisit previous searches. The app also supports searching by current location. ",
    },
    {
        id : 7,
        projectName : "Newflix (Netflix Clone)",
        link : "https://kiranmvarma25.github.io/newflix/intro.html",
        projectThumbnail : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxAKeCk5XF3h43HOiwPOyftDtzfPVPDFVvB_srCV4tCLAlq62A3QgA8RJqB15HY2IaRio&usqp=CAU",
        technologiesUsed : ["HTML", "CSS", "JavaScript"],
        projectDescription : "Users can explore a wide variety of videos organized into different categories for easy navigation. The app offers a user-friendly interface for browsing and discovering content, ensuring a seamless and engaging streaming experience.",
    },
    // {
    //     id : 8,
    //     projectName : "Blog Post Website",
    //     link : "https://kiranmvarma25.github.io/ICC-CWC-23/",
    //     projectThumbnail : "https://m.economictimes.com/thumb/msid-99188557,width-1200,height-900,resizemode-4,imgsize-9102/icc-reveals-logo-for-cricket-world-cup-2023-india-on-12th-anniversary-of-cwc-2011-triumph.jpg",
    //     technologiesUsed : ["HTML", "CSS"],
    //     projectDescription : "Blog on Indian Cricket Team Journey at ICC Cricket World Cup 2023 which held at India, users can find detailed information of matches played by Indian team with videos and also Tournament highlights, Player Stats, Teams participated",
    // },
]